//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkyanusYayincilikWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurumlar
    {
        public int KurumId { get; set; }
        public int IlId { get; set; }
        public int IlceId { get; set; }
        public string Kategori { get; set; }
        public string KurumAdi { get; set; }
    }
}
