//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkyanusYayincilikWebForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class soncuEntities : DbContext
    {
        public soncuEntities()
            : base("name=soncuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Kurumlar> Kurumlar { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Town> Town { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
    
        public virtual int sp_OrdrInsert(Nullable<System.DateTime> orderDate, string customerNameSurname, string customerPhone, string il, string ilce, Nullable<int> kurumId, Nullable<int> urunId)
        {
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("orderDate", orderDate) :
                new ObjectParameter("orderDate", typeof(System.DateTime));
    
            var customerNameSurnameParameter = customerNameSurname != null ?
                new ObjectParameter("customerNameSurname", customerNameSurname) :
                new ObjectParameter("customerNameSurname", typeof(string));
    
            var customerPhoneParameter = customerPhone != null ?
                new ObjectParameter("customerPhone", customerPhone) :
                new ObjectParameter("customerPhone", typeof(string));
    
            var ilParameter = il != null ?
                new ObjectParameter("Il", il) :
                new ObjectParameter("Il", typeof(string));
    
            var ilceParameter = ilce != null ?
                new ObjectParameter("Ilce", ilce) :
                new ObjectParameter("Ilce", typeof(string));
    
            var kurumIdParameter = kurumId.HasValue ?
                new ObjectParameter("KurumId", kurumId) :
                new ObjectParameter("KurumId", typeof(int));
    
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("UrunId", urunId) :
                new ObjectParameter("UrunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_OrdrInsert", orderDateParameter, customerNameSurnameParameter, customerPhoneParameter, ilParameter, ilceParameter, kurumIdParameter, urunIdParameter);
        }
    }
}
